import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import { Sidebar } from "./components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange (optional for smoother transitions)
        >
          
          <div className="min-h-screen flex flex-col">
            {/* <TopBanner /> */}
            <div className="flex flex-1">
              <Sidebar /> {/* Add the Sidebar here */}
              <main className="flex-1">{children}</main> {/* Wrap children in a main tag */}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
